name: Book JUnit Tests

steps:
  - uses: actions/checkout@v3

  - name: Setup Maven
    uses: actions/setup-java@v3
    with:
      java-version: 11  # Adjust Java version as needed

  - name: Cache Maven packages
    uses: actions/cache@v3
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
      restore-keys: |
        ${{ runner.os }}-maven-

  - name: Build project
    run: mvn clean install

  - name: Run JUnit tests
    run: mvn test
