name: Build and Test Book Project

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display Test Message
        run: echo "This a simple test workflow"
        #uses: ./ci-books.yaml@v1  # Include the nested workflow with version (optional)

